# -*- coding: utf-8 -*-
r"""dyn Remember 캐시 → js/data.js 재생성 도구.

원본: 2500726 정수장 python 최적화 v1.dyn — 반드시 Data.Remember 캐시를 보유한
      저장본을 지정할 것(캐시를 비운 사본은 쓸 수 없다 — 스크립트가 FAIL로 알린다).
사용: python tools/extract_cache.py "<dyn 경로>"
인자 없이 실행하면 기존 js/data.js를 덮어쓰지 않고 검사만 한다.
"""
import json
import sys
import os
import io

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "js", "data.js")

# dyn 판독 근거 (2026-08-24 분석):
#  - 라벨: 코드블록 ["1",...,"13"] (9,10,11은 한 박스)
#  - 배치 순서: 박스INDEX 코드블록 0,1,2,3,4,8,7,6,5,10,9 (rec0→rec10 순서로 이 인덱스의 박스를 배치)
#  - 연결쌍: 코드블록 라벨 1-3, 2-3, 3-4, 4-5, 5-6, 6-7, 6-12, 11-12
#  - 시설명: AU 2025 발표 슬라이드 7
LABELS = ["1", "2", "3", "4", "5", "6", "7", "8", "9,10,11", "12", "13"]
PLACE_ORDER = [0, 1, 2, 3, 4, 8, 7, 6, 5, 10, 9]
CONNECTIONS = [[1, 3], [2, 3], [3, 4], [4, 5], [5, 6], [6, 7], [6, 12], [11, 12]]
FACILITY_NAMES = {
    "1": "Intake Basin", "2": "Mixing Basin", "3": "Sedimentation Tank",
    "4": "Rapid Sand Filter", "5": "Ozone Contact Chamber",
    "6": "Activated Carbon Adsorption Basin", "7": "Clear Well",
    "8": "Backwash Pumping Station", "9,10,11": "Discharge/Sludge/Thickener",
    "12": "Dewatering Facility", "13": "Management Facility",
}
# dyn ColorPalette 12종에서 발췌(박스 11개 순서 매핑은 근사)
COLORS = ["#00FFFF", "#00C0FF", "#0080FE", "#00FE01", "#7DFF02", "#FFFF00",
          "#FF7F01", "#FF4000", "#FF0000", "#00FFBF", "#0043FF"]


def load_caches(dyn_path):
    d = json.load(open(dyn_path, encoding="utf-8"))
    caches = []
    for n in d["Nodes"]:
        if "Remember" in n.get("ConcreteType", ""):
            c = n.get("Cache")
            caches.append(json.loads(c) if c else None)
    return caches


def classify(caches):
    """캐시 4개를 내용으로 분류: 11폴리라인=박스, 1폴리라인=대지경계, 원=출입, 점=참조점."""
    boxes = boundary = entries = refpts = None
    for items in caches:
        if not items:
            continue
        kinds = {it["ConcreteType"].split(",")[0].split(".")[-1] for it in items}
        if kinds == {"Polyline"} and len(items) == 11:
            boxes = items
        elif kinds == {"Polyline"} and len(items) == 1:
            boundary = items[0]
        elif kinds == {"Circle"}:
            entries = items
        elif kinds == {"Point"}:
            refpts = items
    missing = [k for k, v in [("boxes", boxes), ("boundary", boundary),
                              ("entries", entries), ("refpts", refpts)] if v is None]
    if missing:
        raise SystemExit(f"FAIL: cache 분류 실패 — 누락 {missing} (캐시가 빈 dyn을 지정했는가?)")
    return boxes, boundary, entries, refpts


def pts(poly):
    return [[round(p["X"], 2), round(p["Y"], 2)] for p in poly["Points"]]


def build(dyn_path):
    boxes_raw, boundary_raw, entries_raw, refpts_raw = classify(load_caches(dyn_path))
    boxes = []
    for i, b in enumerate(boxes_raw):
        pp = pts(b)
        xs = [p[0] for p in pp]
        ys = [p[1] for p in pp]
        boxes.append({
            "idx": i, "label": LABELS[i], "name": FACILITY_NAMES[LABELS[i]],
            "w": round(max(xs) - min(xs), 2), "h": round(max(ys) - min(ys), 2),
            "color": COLORS[i],
        })
    data = {
        "_source": os.path.basename(dyn_path),
        "_units": "mm",
        "_note": "Remember cache direct read; placement order/labels/connections from graph analysis 2026-08-24",
        "boundary": pts(boundary_raw),
        "boxes": boxes,
        "entries": [{"cx": round(c["CenterPoint"]["X"], 2), "cy": round(c["CenterPoint"]["Y"], 2),
                     "r": round(c.get("Radius", 0), 2)} for c in entries_raw],
        "refPoints": [[round(p["X"], 2), round(p["Y"], 2)] for p in refpts_raw],
        "placeOrder": PLACE_ORDER,
        "connections": CONNECTIONS,
    }
    return data


def main():
    if len(sys.argv) < 2:
        if os.path.exists(OUT):
            txt = open(OUT, encoding="utf-8").read()
            payload = txt[txt.index("{"):txt.rindex("}") + 1]
            data = json.loads(payload)
            print(f"CHECK PASS: data.js boundary {len(data['boundary'])}pts, "
                  f"boxes {len(data['boxes'])}, entries {len(data['entries'])}")
        else:
            print("data.js 없음 — dyn 경로를 인자로 지정해 생성할 것")
        return
    data = build(sys.argv[1])
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("// generated by tools/extract_cache.py — do not edit by hand\n")
        f.write("const SITE_DATA = ")
        f.write(json.dumps(data, ensure_ascii=False, indent=1))
        f.write(";\n")
    print(f"OK: {OUT} 생성 — boundary {len(data['boundary'])}pts, boxes {len(data['boxes'])}, "
          f"entries {len(data['entries'])}, refPoints {len(data['refPoints'])}")


if __name__ == "__main__":
    main()
